export const subTopic = [
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": null,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Real Numbers",
    "topicName": "Introduction to Real Numbers",
    "subtopicName": "Commutative law",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note":
      "Real numbers can be defined as the union of both the rational and irrational numbers. They can be both positive or negative and are denoted by the symbol “R”. All the natural numbers, decimals and fractions come under this category. See the figure, given below, which shows the classification of real numerals.",
  },
  {
    "topicId": 0,
    "chapterId": 0,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Real Numbers",
    "topicName": "Introduction to Real Numbers",
    "subtopicName": "Distributive Property",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": 0,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Real Numbers",
    "topicName": "The Fundamental Theorem of Arithmetic",
    "subtopicName": "Prime Factorization Method",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": 0,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Real Numbers",
    "topicName": "Revisiting Irrational Numbers",
    "subtopicName": "How to Expand Rational Numbers in Decimals?",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Polynomials",
    "topicName": "Introduction Polynomials",
    "subtopicName": "Degree of a Polynomial",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Quadratic Equations",
    "topicName": "Solution of a Quadratic Equation by Factorisation",
    "subtopicName": "Range of Quadratic Equation",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": 2,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Quadratic Equations",
    "topicName": "Solution of a Quadratic Equation by Factorisation",
    "subtopicName": "Maximum and Minimum value",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Arithmetic Progressions",
    "topicName": "nth Term of an AP",
    "subtopicName": "Sum of N Terms Formula",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Triangles",
    "topicName": "Similarity of Triangles",
    "subtopicName": "Triangle Proportionality Theorem",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Coordinate Geometry",
    "topicName": "Distance Formula",
    "subtopicName": "Distance Between Two Points",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": 8,
    "chapterId": 5,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Coordinate Geometry",
    "topicName": "Distance Formula",
    "subtopicName": "Coordinates of a point",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Introduction To Trigonometry",
    "topicName": "Trigonometric Ratios",
    "subtopicName": "Trigonometric Ratios Of Standard Angles",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": 9,
    "chapterId": 6,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Introduction To Trigonometry",
    "topicName": "Trigonometric Ratios",
    "subtopicName": "Derivation of Trigonometric Ratios for Standard Angles",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Circles",
    "topicName": " Tangent to a Circle",
    "subtopicName": "What is the Tangent of a Circle?",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
  {
    "topicId": null,
    "chapterId": null,
    "subjectId": 0,
    "grade": "10th",
    "subjectName": "Maths",
    "chapterName": "Statistics",
    "topicName": "Mean of Grouped Data",
    "subtopicName": "Mean Definition in Statistics",
    "url": "https://player.vimeo.com/video/347119375",
    "videoMins": 10,
    "note": "Real numbers can be defined as the union of both the rational and irrational numbers."
  },
];
