export const GET_SUBTOPICS_BY_GRADE = 'getSubtopicsByGrade';
export const GET_SUBTOPICS_BY_GRADE_SUCCESS = `${GET_SUBTOPICS_BY_GRADE}.success`;
export const GET_SUBTOPICS_BY_GRADE_FAILED = `${GET_SUBTOPICS_BY_GRADE}.failed`;

export const GET_SUBTOPICS_BY_SUBJECT = 'getSubtopicsBySubject';
export const GET_SUBTOPICS_BY_SUBJECT_SUCCESS = `${GET_SUBTOPICS_BY_SUBJECT}.success`;
export const GET_SUBTOPICS_BY_SUBJECT_FAILED = `${GET_SUBTOPICS_BY_SUBJECT}.failed`;

export const GET_SUBTOPICS_BY_CHAPTER = 'getSubtopicsByChapter';
export const GET_SUBTOPICS_BY_CHAPTER_SUCCESS = `${GET_SUBTOPICS_BY_CHAPTER}.success`;
export const GET_SUBTOPICS_BY_CHAPTER_FAILED = `${GET_SUBTOPICS_BY_CHAPTER}.failed`;

export const GET_SUBTOPICS_BY_TOPIC = 'getSubtopicsByTopic';
export const GET_SUBTOPICS_BY_TOPIC_SUCCESS = `${GET_SUBTOPICS_BY_TOPIC}.success`;
export const GET_SUBTOPICS_BY_TOPIC_FAILED = `${GET_SUBTOPICS_BY_TOPIC}.failed`;
